/*
implements.js
a list of tools used in cooking
sources: Wikipedia.
*/

module.exports = {
  tools : [
    "Apple corer",
    "Biscuit cutter",
    "Biscuit press",
    "Blow torch",
    "Boil over preventer",
    "Bottle opener",
    "Bowl",
    "Bread knife",
    "Browning tray",
    "Butter curler",
    "Cheese knife",
    "Cheesecloth",
    "Chef's knife",
    "Cherry pitter",
    "Chinois",
    "Cleaver",
    "Colander",
    "Corkscrew",
    "Crab cracker",
    "Cutting board",
    "Dough scraper",
    "Egg piercer",
    "Egg poacher",
    "Egg separator",
    "Egg slicer",
    "Egg timer",
    "Fillet knife",
    "Fish scaler",
    "Fish slice",
    "Flour sifter",
    "Food mill",
    "Funnel",
    "Garlic press",
    "Grapefruit knife",
    "Grater",
    "Gravy strainer",
    "Herb chopper",
    "Ladle",
    "Lame",
    "Lemon reamer",
    "Lemon squeezer",
    "Lobster pick",
    "Mandoline",
    "Mated colander pot",
    "Measuring cup",
    "Measuring spoon",
    "Meat grinder",
    "Meat tenderiser",
    "Meat thermometer",
    "Melon baller",
    "Mezzaluna",
    "Mortar and pestle",
    "Nutcracker",
    "Nutmeg grater",
    "Oven glove",
    "Pastry bag",
    "Pastry blender",
    "Pastry brush",
    "Pastry wheel",
    "Peel",
    "Peeler",
    "Pepper mill",
    "Pie bird",
    "Pizza cutter",
    "Potato masher",
    "Potato ricer",
    "Pot-holder",
    "Poultry shears",
    "Roller docker",
    "Rolling pin",
    "Salt shaker",
    "Scale",
    "Scissors",
    "Scoop",
    "Sieve",
    "Slotted spoon",
    "Spatula",
    "Spider",
    "Sugar thermometer",
    "Tamis",
    "Tin opener",
    "Tomato knife",
    "Tongs",
    "Trussing needle",
    "Twine",
    "Whisk",
    "Wooden spoon",
    "Zester"
  ],
  cookware : [
  "Baking pan",
  "Beanpot",
  "Chip pan",
  "Cookie sheet",
  "Cooking pot",
  "tava",
  "Double boiler",
  "Doufeu",
  "Dutch oven",
  "Food processor",
  "Skillet",
  "Griddle",
  "Karahi",
  "Kazan",
  "Kettle",
  "Pan",
  "Pressure cooker",
  "Ramekin",
  "Roasting pan",
  "Roasting rack",
  "Saucepan ",
  "Saucier ",
  "Sauté pan",
  "Splayed Sauté pan",
  "Soufflé dish",
  "Springform pan",
  "Stockpot",
  "Tajine",
  "Tube pan",
  "Wok",
  "Wonder Pot",

  "Air fryer",
  "Bachelor griller",
  "Barbecue",
  "Barbecue grill",
  "Big Green Egg",
  "Beehive oven",
  "Brasero",
  "Brazier",
  "Bread machine",
  "Brown Bobby",
  "Burjiko",
  "Butane torch",
  "Cheesemelter",
  "Chocolatera",
  "Chorkor oven",
  "Clome oven",
  "Comal",
  "Combi steamer",
  "Communal oven",
  "Convection microwave",
  "Convection oven",
  "Corn roaster",
  "Crepe maker",
  "Deep fryer",
  "Earth oven",
  "Electric cooker",
  "Energy regulator",
  "Espresso machine",
  "Field kitchen",
  "Fire pot",
  "Flattop grill",
  "Food steamer",
  "Fufu Machine",
  "Halogen oven",
  "Haybox",
  "Horno",
  "Hot Box",
  "Hot plate",
  "Kamado",
  "Kettle",
  "Kitchener range",
  "Kujiejun",
  "Kyoto box",
  "Masonry oven",
  "Mess kit",
  "Microwave oven",
  "Multicooker",
  "Oven",
  "Pancake machine",
  "Panini sandwich grill",
  "Popcorn maker",
  "Pressure cooker",
  "Pressure fryer",
  "Recke multicooker",
  "Reflector oven",
  "Remoska",
  "Rice cooker",
  "Rice polisher",
  "Roasting jack",
  "Rocket mass heater",
  "Rotisserie",
  "Russian oven",
  "Sabbath mode",
  "Salamander broiler",
  "Samovar",
  "Sandwich toaster",
  "Self-cleaning oven",
  "Set-n-Forget cooker",
  "Shichirin",
  "Slow cooker",
  "Solar cooker",
  "Sous-vide cooker",
  "Soy milk maker",
  "Stove",
  "Susceptor",
  "Tabun oven",
  "Tandoor",
  "Tangia",
  "Thermal immersion circulator",
  "Toaster and toaster ovens",
  "Turkey fryer",
  "Vacuum fryer",
  "Waffle iron",
  "Wet grinder",
  "Wood-fired oven"
  ]
}
